parameters:
    translation.domain.app: app
    translation.domain.default: '%translation.domain.app%'

framework:
    default_locale: fr
    enabled_locales: ['en', 'fr']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['fr']
