version: '3'

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'project'
    networks:
      - myavatar

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    links:
      - "database:db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_PASSWORD: root
      PMA_USER: root
    networks:
      - myavatar

  maildev:
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    networks:
      - myavatar

volumes:
  database_data:

networks:
  myavatar:
